version: '3'
services:
  setuser:
    container_name: setuser
    image: setuser:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s