name: Postgres10

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - master

jobs:
  pg13:
    name: Postgres10
    runs-on: ubuntu-latest
    env:
      PG_VER: "10"
      DOCKER_DIR: ${{ github.workspace }}/.github/docker
      RESOURCE_DIR: ${{ github.workspace }}/.github/resources
      SCRIPT_DIR: ${{ github.workspace }}/.github/resources/scripts
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Build set_user
        run: |
          docker build -t setuser:latest ${{ env.DOCKER_DIR }}/pg${{ env.PG_VER }}

      - name: Run PG set_user
        run: |
          docker-compose -f ${{ env.RESOURCE_DIR }}/setuser.yml up -d
          /bin/bash ${{ env.SCRIPT_DIR }}/healthcheck.sh setuser 60

      - name: Run tests
        run: |
          docker exec setuser make -C /opt/set_user USE_PGXS=1 REGRESS_OPTS='--user=postgres' installcheck
    
      - name: Docker Log
        if: always()
        run: |
          docker cp setuser:/opt/set_user/results/set_user.out ./set_user.out
          docker logs setuser > setuser_container.out 2>&1
    
      - name: Copy regression diff
        continue-on-error: true
        run: |
          docker cp setuser:/opt/set_user/results/regression.diffs ./regression.diffs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: |
            *.out
            *.diffs
