# CI for set_user Pull Requests and pushes to the cicd branch.
# Runs regression tests against all supported versions of postgres.
on:
  push:
    branches:
      - cicd*
  pull_request:
    branches:
      - master

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_DIR: ${{ github.workspace }}/.github/docker
      RESOURCE_DIR: ${{ github.workspace }}/.github/resources
      SCRIPT_DIR: ${{ github.workspace }}/.github/resources/scripts
    strategy:
      matrix:
        pgver: [9.4, 9.5, 9.6, 10, 11, 12, 13, 14, 14beta3]
        include:
          - pgver: 14beta3
            devpkg: 14
    steps:
      - name: Checkout set_user repo
        uses: actions/checkout@v2.3.4

      - name: Build set_user
        run: |
          DEVPKG=${{ matrix.devpkg }}
          [ -z "$DEVPKG"] && DEVPKG=${{ matrix.pgver }}
          docker build -t set_user:latest \
                --build-arg PGVER=${{ matrix.pgver }} \
                --build-arg DEVPKG=$DEVPKG \
                -f ${{ env.DOCKER_DIR }}/Dockerfile .

      - name: Run PG set_user
        run: |
          docker-compose -f ${{ env.RESOURCE_DIR }}/set_user.yml up -d
          /bin/bash ${{ env.SCRIPT_DIR }}/healthcheck.sh set_user 60

      - name: Run tests
        run: |
          docker exec set_user make -C /src/set_user USE_PGXS=1 REGRESS_OPTS='--user=postgres' installcheck

      - name: Show any regression diffs
        if: ${{ failure() }} 
        run: |
          docker cp set_user:/src/set_user/regression.diffs ./regression.diffs
          cat ./regression.diffs
